version: "3.8"
services:
  db:
    image: mysql
    platform: linux/arm64/v8
    container_name: mysql-db
    ports: 
      - '${MYSQL_PORT}:3306'
    environment: 
      MYSQL_CONTAINER_NAME: "${MYSQL_CONTAINER_NAME}"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
    command: # 명령어 실행
      - '--character-set-server=utf8mb4'
      - '--collation-server=utf8mb4_unicode_ci'
    volumes: 
      - "./db:/var/lib/mysql"
      - "./db:/var/lib/nestjsDB"
    env_file:
      - .env